fix: attributes udpate: be mindful of the subset of attributes being …
mendersoftware/inventory pull request #401
Opened 2023-08-02 10:09 UTC by merlin-northern

…patched.

Changelog: Title
Ticket: MEN-6643

2023-08-02 12:21 UTC, merlin-northern commented
@mender-test-bot start pipeline --fast --sugar please

2023-08-02 12:22 UTC, merlin-northern commented
@alfrunes give me green light on this idea, and I will add tests.

2023-08-03 14:54 UTC, alfrunes requested changes
This does not check if some of the attributes removed. To be honest, this implementation is starting to get really complicated to follow...
Why can't we just do a very simple implementation in the app layer for the PUT/PATCH devices APIs? Something along the lines of:
 1. Sort (stable) the attributes (by name)
 2.  Remove duplicates (preserve last entry)
 3. Fetch attributes from database
 4. Sort attributes and filter by scope == "inventory"
 5. Compare the two sets of attributes

2023-08-04 06:51 UTC, merlin-northern commented on api/http/api_inventory.go
> +		// is a conscious choice of the caller, to write to the db unconditionally.
@alfrunes heads up here: shall we keep it only in the PATCH or also check in PUT where we replace all the attributes (I am having some doubts about introducing the check in the latter case as well) (if we want this, `InventoryNeedsUpdate` will need a small update)

2023-08-04 06:54 UTC, merlin-northern commented
> This does not check if some of the attributes removed. To be honest, this implementation is starting to get really complicated to follow... Why can't we just do a very simple implementation in the app layer for the PUT/PATCH devices APIs? Something along the lines of:
> 
> 1. Sort (stable) the attributes (by name)
> 2. Remove duplicates (preserve last entry)
> 3. Fetch attributes from database
> 4. Sort attributes and filter by scope == "inventory"
> 5. Compare the two sets of attributes

okey, my friend. what do you think now?

2023-10-04 10:56 UTC, alfrunes commented
Closing as this PR is getting stale.

2023-10-04 10:56 UTC, closed without merging